import { ContextProvider } from "@/contex/context";
import "./globals.css";
import Link from "next/link";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className="flex bg-slate-400 text-white text-lg flex-row gap-4">
          <Link href={"/about"}>about</Link>
          <Link href={"/test"}>test</Link>
          <Link href={"/api/user"}>user api</Link>
          <Link href={"/add"}>add </Link>
        </div>

        <ContextProvider >{children}</ContextProvider>
      </body>
    </html>
  );
}
